[package]
name = "pico2w-downloader-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.3"
crc = "3.0"
ihex = "3.0"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.17" # For progress bar
